shinygwas:
  image: dnadave/release_shinydemo:oct2016
  ports:
  - "${HOST_PORT}:80/tcp"
  labels:
    io.rancher.container.pull_image: always
  tty: true
  hostname: axiohost13
  stdin_open: true
  net: bridge
  privileged: true
